# Simple workflow for deploying static content to GitHub Pages
name: deploy-notebooks

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy-notebooks:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
  
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - name: Setup Enviroment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Installing depedencies
        run: |
          pip install -r requirements.txt
  
      - name: Build the book
        run: |
          jupyter-book build .
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '_build/html'
          
    # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
